"""Generate counties.dat for ShackLog from the US Census FIPS county file.

Source: https://www2.census.gov/geo/docs/reference/codes2020/national_county2020.txt
(US Census Bureau, public domain.)
"""
import re, io, collections, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else 'fips.txt'
DST = sys.argv[2] if len(sys.argv) > 2 else 'counties.dat'

ADMIN = r'\b(COUNTY|PARISH|CITY AND BOROUGH|BOROUGH|CENSUS AREA|MUNICIPALITY|MUNICIPIO)\b'

def match_key(name):
    """Normalised key the matcher compares against.

    An independent city KEEPS its CITY marker.  Virginia, Maryland and
    Missouri have six name pairs where a county and a legally separate
    independent city share a name (Baltimore County / Baltimore city;
    Fairfax, Franklin, Richmond, Roanoke; St. Louis).  They are distinct
    entities that a QSO party scores separately, so folding both to one
    key would silently merge two counties into one.
    """
    upper = name.upper()
    independent_city = upper.endswith(' CITY') and 'CITY AND BOROUGH' not in upper
    s = re.sub(ADMIN, '', upper)
    if not independent_city:
        s = re.sub(r'\bCITY\b', '', s)
    s = re.sub(r'\bSAINTE?\b', 'ST', s)
    s = re.sub(r'\bSTE\b', 'ST', s)
    s = s.replace('.', '').replace("'", '').replace('-', ' ')
    s = re.sub(r'\s+', ' ', s).strip()
    # Only the three USVI districts drop a trailing ISLAND, matched BY NAME.
    # A general 'ends in ISLAND' rule cannot work: it must give the same
    # answer for the stored Census name ('Rock Island County', which keeps
    # ISLAND because it carries County) and for what an operator actually
    # types ('Rock Island', which has no suffix to key off). Keying off the
    # query text alone turned IL,Rock Island into ROCK.
    # Must stay identical to CountyList::normalize() in src/CountyList.cpp.
    if re.match(r'^(ST|SAINT) (CROIX|JOHN|THOMAS) ISLAND$', ' '.join(s.split())):
        s = re.sub(r'\s+ISLAND$', '', s)
    if independent_city and not s.endswith(' CITY'):
        s = (s + ' CITY').strip()
    return s

rows = [l.rstrip('\n').split('|')
        for l in open(SRC, encoding='utf-8').read().splitlines()[1:] if l.strip()]

out = io.StringIO()
out.write("""# counties.dat - US county / parish / borough reference for ShackLog
#
# Source: US Census Bureau 2020 FIPS county codes (public domain)
#   https://www2.census.gov/geo/docs/reference/codes2020/national_county2020.txt
# Generated by tools/gen_counties.py - do not hand-edit.
#
# Format, one record per line, pipe-separated:
#   STATE|FIPS|Canonical Name|Match Key
#
# Canonical Name is the Census name verbatim, including its administrative word
# (County / Parish / Borough / city / Municipio), because that is what a QSO
# party exchange and an ADIF CNTY field actually carry.
#
# Match Key is the normalised form the matcher compares against: uppercased,
# administrative word removed, punctuation stripped, Saint folded to ST.
# Independent cities keep a trailing CITY, because six of them share a name
# with a county in the same state and are scored separately.
#
# Blank lines and lines beginning with # are ignored.
#
""")

seen = collections.Counter()
n = 0
for r in sorted(rows, key=lambda r: (r[0], r[4])):
    st, fips, name = r[0], r[1] + r[2], r[4]
    k = match_key(name)
    seen[(st, k)] += 1
    out.write("%s|%s|%s|%s\n" % (st, fips, name, k))
    n += 1

open(DST, 'w', encoding='utf-8', newline='\n').write(out.getvalue())
print("wrote %s: %d records" % (DST, n))
dups = {k: v for k, v in seen.items() if v > 1}
print("COLLISIONS (same state+key):", len(dups))
for k, v in sorted(dups.items()):
    print("   ", k, v)
